# Generated by Django 4.2.15 on 2024-12-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, db_column='last_update_date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, db_column='last_update_date'),
        ),
    ]
