# Generated by Django 4.2.15 on 2024-12-03 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_comment_last_update_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=128)),
                ('family', models.CharField(db_column='family', max_length=128)),
                ('age', models.IntegerField(db_column='age', default=0)),
                ('gender', models.CharField(choices=[('m', 'male (man)'), ('f', 'female (woman)')], db_column='gender', max_length=1)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='custom_user',
            field=models.ForeignKey(db_column='custom_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='news.customuser'),
        ),
    ]
