# Generated by Django 4.2.17 on 2025-01-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='category',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='category',
            field=models.ManyToManyField(db_column='category_id', to='news.category'),
        ),
    ]
