# Generated by Django 4.2.17 on 2025-01-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_subscriber_category_subscriber_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(db_column='category_id', to='news.category'),
        ),
    ]
