# Generated by Django 4.2.17 on 2025-01-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_post_category_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='category',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='category',
            field=models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
    ]
