# Generated by Django 4.2.17 on 2025-01-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_subscriber_category_subscriber_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('uuid', models.CharField(db_column='uuid', max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_column='datetime')),
                ('description', models.TextField(db_column='description')),
                ('mailing', models.ForeignKey(db_column='mailing', on_delete=django.db.models.deletion.CASCADE, to='news.mailing')),
                ('posts', models.ManyToManyField(db_column='posts', to='news.post')),
            ],
        ),
    ]
