# Generated by Django 4.2.17 on 2025-01-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_mailing_mailinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='description',
            field=models.TextField(db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='posts',
            field=models.ManyToManyField(db_column='posts', null=True, to='news.post'),
        ),
    ]
