# Generated by Django 4.2.17 on 2025-01-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_mailinglog_description_alter_mailinglog_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='posts',
            field=models.ManyToManyField(blank=True, db_column='posts', to='news.post'),
        ),
    ]
