# Generated by Django 4.2.17 on 2025-02-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_mailinglog_posts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique appversion'),
        ),
    ]
